shallow_clone: true

# version format
version: 1.0.{build}

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

cache:
  - packages -> **\packages.config
  - Tulpep.Signtul.Website\bower_components -> **\bower.json
  - Tulpep.Signtul.Website\node_modules -> **\package.json

configuration: Release
platform:
  - x86
  - Any CPU

install:
  - cmd: Tulpep.Signtul.Website\Grunt-Bat.cmd

# Assembly Info
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"


environment:
  pfx_password:
    secure: yfky3xGsKE0Kwe2xOHB2sQ==
  DEFAULT_CONNECTION_STRING:
    secure: k6cxbaFYPWShDiz00J2CcYdWCqsOen3i3LpfwpMgviHMCo1plnpp23OHRoOI+W3zpikgCUZuNDPZuUP/ahwyhzBYubdo6zuA+rcnMwKMKk3AYW5NJBcoBsiVv+24/J9RKdEz8K0SPQBbk6Im9Vug7QAVx6zJOcL9pmavzxpmTyvmAsHtJQPcfnGWEeju80epT+5e8xZndKe7iAVJOr/4gGFNGGIBs0/T8Ag1FUUjH8Wn//VSC9FbLQIt0+DnVqJ9OZx2BaF5/lic+PxSA5v67Pz4zjbFVHB/Zk+JZPtFUFM=
  AZURE_STORAGE_CONNECTION_STRING:
    secure: CPrTWFks82XkQKQeS7a0c7CPh0G+n4mIkeqDLlKm/vjgWtrRmuPIbmsSj38pxDdnea/Npld0Iff4Fnlzmjr2epEL4zD7DTYef10Fs83Ski1bfqMsrY+el0rjPZDUveUNnSb7sFtt6NDyDrVSmlgsDlOuppAK2A+wZVR91I1kfb4jsEi4ubMYg/N+ajrxhbtkdZINKVjSry1oQrvcymDcKA==
  SENDGRID_ACCOUNT:
    secure: 9oBBNBZ539xjTmOMj/Xs2XiovdUZS1MxBhPDrH0CYY9VcyT8OFfixkBhWCIXDclMTqcv6WxiVqrfhHQHjEFOKA==
  SENDGRID_PASSWORD:
    secure: arH7Y5UriAWusmyH9iBV8g==
  REDIS_KEY:
    secure: Ga2eljsgadgExQVHhi3ZXtKHPlUkEH5FcV4BeiJanGT6ZZ8Edobk29IsYrGUm3in
  INTERNAL_API_KEY:
    secure: A0YiqKSyt0TnDJZxe919alYVc4HGvIEwk9a/SyftGXfdf5HUeBiECl3OMg78EyKmrFkntcjHE2M+PJszpRnQoQ==
  IDA_APPKEY:
    secure: jjs5l3ISruXRKYb9ybaNrazKSy1S7CJj0YQ/ZuYFq05KCzEXnDID/yI4FABC/N+9
  RECAPTCHA_SECRET_KEY:
    secure: tyNrkoJDGwTQkpOqUtW/LJ8Wrhdn2jU9zuLL0Fp7DgKKtFSSzapt/uBtz7E2dTYY

before_build:
  ##Set registry key with PFX password and run script to install cert
  - ps: New-Item -path HKCU:\SOFTWARE\Tulpep
  - ps: New-ItemProperty -path HKCU:\SOFTWARE\Tulpep -Name PfxPassword -Value $env:pfx_password | Out-Null #Out-Null because we dont want to see the password in the console
  - ps: .\InstallCertificate.ps1
  - ps: .\CreateBuildTxt.ps1

build:
  publish_wap: true

after_test:
  - ps: .\Nuget\build.ps1

artifacts:
  - path: '**\SigntulOutlookAddin*.nupkg'
    name: Tulpep.Signtul.OutlookAddIn
  - path: '**\SigntulActiveDirectorySync*.nupkg'
    name: Tulpep.Signtul.ActiveDirectory



#Deployment configuration
deploy:
  - provider: WebDeploy
    server: https://signtul.scm.azurewebsites.net:443/msdeploy.axd?site=signtul
    name: signtul
    website: signtul
    username: $signtul
    password:
      secure: VcIZAkcBYKHy+xEqKbpuFW+py+iZ3vtI1Uj7xs+7RHgnhYCRYHsacyObqUsQNcO00O62s33iiKu1U9fjxWYiRQ==
    ntlm: false
    remove_files: true
    app_offline: false
    artifact: Tulpep.Signtul.Website
    on:
      branch: master
      platform: Any CPU

  - provider: WebDeploy
    server: https://signtul-internal.scm.azurewebsites.net:443/msdeploy.axd?site=signtul-internal
    name: signtul-internal
    website: signtul-internal
    username: $signtul-internal
    password:
      secure: 8ltsvTi6v/95jZtVmq0iiM41SES2UbG9FiHbjA9Cz2ckKboAUPXxV1NrGDtLXddFOok/3PEV0c1TxMh3vPHGfw==
    ntlm: false
    remove_files: true
    app_offline: false
    artifact: Tulpep.Signtul.AdminWebsite
    on:
      branch: master
      platform: Any CPU

notifications:
  - provider: Slack
    auth_token:
      secure: ix/RPtJFKVtUmn022JjXn/YXrzLp1dHklMrTfm6JAe73h6GqVKIpNaPrneqe0Qjh
    channel: signtul
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
